name: Android Build and Deployment Pipeline

on:
  pull_request:
  push:
    branches:
      - main
      - 'release_*'

jobs:
  build:
    name: Setup environment and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Generate AAR
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload AAR file
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: analyticSDK/build/outputs/aar/analyticsSDK-release.aar
